#This is a simple poem...
print("There was once a movie star icon, \nWho preferred to sleep with the light on, \nThey learned how to code, \nA device that sure glowed, \nAnd lit up the night using Python \n\t-Anonymous...")
