#This is a comment, it will not print...
#This says Hello World...
print('Hello World')
#This is another example...
print("This uses double quotes")
#Quotes are characters while quotation is the use quotes...
print("""This uses triple quotation...
it will be displayed however I type it""")
#This is an exampe of the use of single quotes against double quotes...
print('''I could do same with single quotes...
See?''')
#This is another way of printing a new line as against triple quotation...
print("This uses a backslash then an n.... \nIt's used to signify a new line")